### ISSUE TITLE
download-files: initial release

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-client#22]
If a user wishes to download files belonging to a record, the current technique is to list file locations:

```console 
$ cernopendata-client get-file-locations --recid 5500 --protocol http
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/BuildFile.xml
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/HiggsDemoAnalyzer.cc
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/List_indexfile.txt
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/M4Lnormdatall.cc
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/M4Lnormdatall_lvl3.cc
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/demoanalyzer_cfg_level3MC.py
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/demoanalyzer_cfg_level3data.py
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/demoanalyzer_cfg_level4MC.py
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/demoanalyzer_cfg_level4data.py
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/mass4l_combine.pdf
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/mass4l_combine.png
```

and then launch `wget` or `curl` commands to download them.

The goal of this issue is to simplify this process by introducing new command `download-files` that would do this for the user.

Possible options:

```console
$ cernopendata-client download-files --recid 5500 --protocol http --parallel-processes 2
```

This would launch two parallel downloading processes, using a suitable Python library, to download the files into current directory.

P.S.: MVP is simply to download files; resuming interrupted downloads will be part of another issue, but it is good to think about this functionality upfront.

P.S. An option `--target-directory` could be introduced which would recreate directory structure known from the original record.  This will be important for AOD files which have subdirectory structure such as [this one](https://eospublichttp.cern.ch/eos/opendata/cms/Run2010A/BTau/AOD/Apr21ReReco-v1).  So the corresponding subdirectories would have to be created in the target directory.

**Comment by tiborsimko** [comment]
Example record to support in this issue: 5500.

The "harder" use case of recrord 1 with index files was separated into issue #25.

**Comment by ParthS007** [comment]
Documenting here the options to test the download files functionality
- Pycurl
- Requests with chunk sizes
- Asyncio

I will be going ahead with these options and check the time taken in downloading and if they are compatible with Python 2 and 3 both.

@tiborsimko Can you please provide a `recid` with large files. Total maybe around (5 gigs)

**Comment by tiborsimko** [comment]
> @tiborsimko Can you please provide a recid with large files. Total maybe around (5 gigs). I will test with 5500 first.

- one O(5GB) file: record ID 3851 or 3853 
- one O(20GB) file: record ID 15007 
- several O(20GB) files in one record: record ID 15001
