### ISSUE TITLE
download-files: xrootd protocol

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-client#24]
In addition to http protocol implemented in #22, we should add support for xrootd protocol which provides more bandwidth.

Check whether client system contains xrootd commands (`xrdcp`) or Python libraries (`xrootd`).

If yes, enable support for `--protocol root`.

If not, report help string what people has to do do install them.

This is not an MVP functionality for the first public release; it can be added later.

**Comment by tiborsimko** [comment]
Regarding Python libraries, we could use upstream [xrootd](https://pypi.org/project/xrootd/) or even our [xrootdpyfs](https://pypi.org/project/xrootdpyfs/).

**Comment by ParthS007** [comment]
Both options look good to me. 👍

**Comment by tiborsimko** [comment]
This will need to amend also `Dockerfile` to have `xrootd` support there.  There are two options:

a) Currently we are based on `python:3.8-slim` which is basically a stripped-down Debian distribution. Either we compile `xrootd` there in the usual way, or look for`xrootd` packages, e.g. for Ubuntu 18.04 LTS one can use:

```console
$ echo 'deb http://storage-ci.web.cern.ch/storage-ci/debian/xrootd/ bionic master' >> /etc/apt/sources.list
$ curl -sL http://storage-ci.web.cern.ch/storage-ci/storageci.key | apt-key add -
$ apt-get update
$ apt-get install xrootd-client
``` 

b) We can switch our base image to CentOS7, which is what CERN batch farms typically use, where `xrootd` can be installed via EPEL:

```console
$ yum install epel-release
$ yum update
$ yum install xrootd-client
```

Note that we have some prior art in `opendata.cern.ch` repository (see its `Dockerfile`) or in `reana-env-root6` (this is for ROOT, but analogously one can do `xrootd`).

@ParthS007 please let me know if you shall look into adding `xrootd` to our Docker image yourself or whether I should.
