### ISSUE TITLE
docs: ReadTheDocs builds fail due to pycurl

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-client#40]
After addition of `pycurl`, the ReadTheDocs builds fail with:

```
   FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
```

This is most probably because some system dependencies such as `libssl-dev` and friends are not installed.

Investigate a best solution to fix the documentation builds.  
- Perhaps add these libraries if RTD build system allows this?
- Perhaps use `autodoc_mock_imports`?

**Comment by ParthS007** [comment]
@tiborsimko this can be closed now?

**Comment by tiborsimko** [comment]
I thought of looking into generating the CLI API in other way... E.g. we could run click-sphinx locally and add the file into `docs` so that ReadTheDocs would simply consume it from there.  (A bit like we are doing with OpenAPI stuff in REANA.) Hence I used `addresses` and not `closes` yet... I'll move the issue into "Ready for work" kanban column.

**Comment by tiborsimko** [comment]
Closing for v0.1.0 release, we can attack this later.
