### ISSUE TITLE
docs: enrich CLI API page

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-client#55]
Let's enrich the CLI API docs page with all commands and options that would be automatically generated.

```
I thought of looking into generating the CLI API in other way... E.g. we could run click-sphinx
locally and add the file into `docs` so that ReadTheDocs would simply consume it from 
there.  (A bit like we are doing with OpenAPI stuff in REANA.) Hence I used `addresses` 
and not `closes` yet... I'll move the issue into "Ready for work" kanban column.
```

_Originally posted by @tiborsimko in https://github.com/cernopendata/cernopendata-client/issues/40#issuecomment-694109978_

**Comment by ParthS007** [comment]
@tiborsimko Can you please explain a bit more about the expected result from this issue?

What I have understood is we have to generate the CLI docs with help of `sphinx-click`.

**Comment by tiborsimko** [comment]
The higher goal is to have an up-to-date info about CLI commands and options on ReadTheDocs here: https://cernopendata-client.readthedocs.io/en/latest/cliapi.html 

However, we cannot install project on ReadTheDocs due to `pycurl` dependency troubles.

Two solutions:

1. Make pycurl optional, see #78. This will make the package installable also on ReadTheDocs, solving the main goal that way. 
2. Generate `cliapi.md` content locally on our laptops while developing, with each feature branch, so that ReadTheDocs wouldn't have to. This is a bit similar to REANA and how `docs/openapi.json` is generated. See e.g. `reana-workflow-controller` and its `run-tests.sh` and `scripts/generate_openapi_spec.py`. We'd have to develop something similar for click-generated docs.

**Comment by ParthS007** [comment]
@tiborsimko 

I have made PR for #78 going for first option. We can turn on the project installation on RTD to check if cli docs are building on their own.
