### ISSUE TITLE
printer: initial release 

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-client#61]
Instead of having `print()` and `click.echo()` hard-coded throughout the code base, let's introduce a new `printer.py` module that can take care of displaying info/error messages in unified manner.

Example: `display_message()` function in `reana-dev`.

We could then print success in green, progress in yellow, errors in red, etc.

The code base should then be amended to use the new `display_message()` function instead of printing or echoing.

**Comment by tiborsimko** [comment]
Don't hesitate to play also with echoing the main headlines in bold, for example:

![2020-10-16-135211_2560x1440_scrot](https://user-images.githubusercontent.com/517546/96255327-03ac7e00-0fb7-11eb-934e-9fa6822ebb94.png)

Example of function signature: `display_message(message, style='error')` which would produce message with leading `==> ERROR: message` in red. By default the style could be green (meaning all OK), and `style='warning'` would be in yellow, etc.

**Comment by ParthS007** [comment]
@tiborsimko What do you think about this one?
<img width="657" alt="Screenshot 2020-10-16 at 14 33 28" src="https://user-images.githubusercontent.com/24358501/96258649-9b609b00-0fbc-11eb-8ecc-02e8d914e4d9.png">
