### ISSUE TITLE
tests: add test for record with TXT and JSON files.

### ISSUE THREAD

**Issue by ParthS007** [cernopendata/cernopendata-client#76]
Discussion on MM:

> This is for big dataset records, and we always have a record with both TXT and JSON files.  (In the past we had a mixture so that some records did not have yet JSON file, but nowadays all do.)
    The codebase should be ready to assume there might be missing, but actually we don't have any "live" test records... We would have to use mock and mock the REST API reply to have a test case.  Which might be a good thing to do to catch all those various non-live corner cases that the client should be ready to deal nicely with...

**Comment by tiborsimko** [comment]
TXT file example:

```console
$ cernopendata-client get-file-locations --recid 5500 | grep txt
http://opendata.cern.ch/eos/opendata/cms/software/HiggsExample20112012/List_indexfile.txt
```

JSON file example:

```console
$ cernopendata-client get-file-locations --recid 14200
http://opendata.cern.ch/eos/opendata/cms/validated-runs/Commissioning10/Commissioning10-May19ReReco_900GeV.json
```

**Comment by ParthS007** [comment]
Added test for `--recid 282` which has `json` and `txt` files in #91
