### ISSUE TITLE
protocol: add 'https' option

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-client#84]
We are deploying support for HTTPS for CERN Open Data portal, e.g. see https://opendata-dev.cern.ch

It would be therefore good to allow `https` protocol everywhere, so that we shall offer three protocols: `http`, `https`, and `xrootd`. 

We should amend the checker etc and also mention this in the documentation.

**Comment by mvidalgarcia** [comment]
All these should be accessible now:
- https://opendata.cern.ch
- https://opendata-qa.cern.ch
- https://opendata-dev.cern.ch
- http://opendata.cern.ch
- http://opendata-qa.cern.ch
- http://opendata-dev.cern.ch
